version: '3.8'

services:
  db:
    image: postgres:17.4
    environment:
      POSTGRES_DB: test-sentry
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test-sentry
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: